spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/department?useUnicode=true&characterEncoding=utf8&serverTimezoneGMT%2B8&useSSL=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
